### PR TITLE
Make UUID implement java.io.Serializable on jvm

### PR DESCRIPTION
**Pull request by mklkj**

### CODE REVIEW

**Comment by hfhbd** [comment]
Can you please add a use-case? Why do you need broken by design Java serialization? There is already support for kotlinx serialization. 
Also, the current implementation does not support persistent serialization.

**Comment by Melodeiro** [comment]
Using UUID with neo4j OGM library requires IDs to implement java.io.Serializable, so it would be nice to have the same entity for ID from db and the one which is passed between the multiplatform client and the server, for example

**Comment by hfhbd** [comment]
@mklkj Why do you need Serializable? What about `Parcelable` support instead? See https://github.com/hfhbd/kotlinx-uuid/pull/297

@Melodeiro How do you test multiplatform clients when using JVM Serializable, eg on your backend server only?

**Comment by mklkj** [comment]
@hfhbd `Serializable` was just the simplest and sufficient way to solve my problem. `Parcelable` will work too

**Pull request closed without merging**
